/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqlloader;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        SqlLoaderApp classUnderTest = new SqlLoaderApp();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
